#version: "3.4"
services:
    mssql:
        image: "mcr.microsoft.com/mssql/server:2022-latest"
        environment:
            SA_PASSWORD: "dataBase@2334"
            ACCEPT_EULA: "Y"
        ports:
            - 1433:1433
        healthcheck:
            test: /opt/mssql-tools/bin/sqlcmd -S localhost -U sa -P "$$SA_PASSWORD" -Q "SELECT 1" || exit 1
            interval: 10s
            timeout: 3s
            retries: 10
            start_period: 10s
        volumes:
            - ./sql-scripts:/usr/src/db
        working_dir: /usr/src/db
        # run the entrypoint.sh that will import the data AND sqlserver
        command: sh -c ' chmod +x ./entrypoint.sh; ./entrypoint.sh & /opt/mssql/bin/sqlservr;'

    app:
        image: node:18
        container_name: app
        working_dir: /usr/src/app
        volumes:
            - ./app:/usr/src/app
        #command: bash -c "npm install && npm start"
        command:
            - /bin/bash
            - -c
            - |
                npm install
                npm install -g nodemon
                nodemon start
        restart: on-failure
        ports:
            - 4000:4000
        depends_on:
            mssql:
                condition: service_healthy
        environment:
            - DB_HOST=mssql
            - DB_USER=sa
            - DB_PASSWORD=dataBase@2334
            - DB_NAME=Silberschatz
            # - DB_PORT=3306
        stdin_open: true
        tty: true

    # version: '3.8'

    # services:
    #   mssql:
    #     image: mcr.microsoft.com/mssql/server:2012-latest
    #     container_name: sql-server
    #     environment:
    #       - SA_PASSWORD=yourStrong(!)Password
    #       - ACCEPT_EULA=Y
    #     healthcheck:
    #       test: ["CMD", "/opt/mssql-tools/bin/sqlcmd", "-Usa", "-PyourStrong(!)Password", "-Q", "select 1"]
    #       interval: 1s
    #       retries: 20
    # volumes:
    #   - ./sql-scripts:/scripts
    #     ports:
    #       - "1435:1433"
